version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    network_mode: host
    restart: always
    user: "120"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://n100d:514"
        tag: "loki"
        mode: non-blocking
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - /ext/loki:/ext/loki
    command: -config.file=/etc/loki/config.yml
