version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    network_mode: host
    restart: always
    user: "120"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - /ext/loki:/ext/loki
    command: -config.file=/etc/loki/config.yml

  alloy:
    image: grafana/alloy:latest
    network_mode: host
    restart: always
    depends_on:
      - loki
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /etc/alloy/snmp_localbuild.yml:/etc/alloy/snmp_localbuild.yml:ro
      - /ext/alloy:/ext/alloy
      - /var/log/nginx:/var/log/nginx:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command: run /etc/alloy/config.alloy --storage.path=/ext/alloy
