version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.5.2
    network_mode: host
    restart: always
    user: "115"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://n100d:514"
        tag: "grafana"
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_SERVER_ROOT_URL: https://home.steenburg.net/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_AUTH_DISABLE_LOGIN: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_INSTALL_PLUGINS: grafana-pyroscope-app,grafana-lokiexplore-app
      GF_RENDERING_SERVER_URL: http://localhost:8081/render
      GF_RENDERING_CALLBACK_URL: http://localhost:3000/grafana/

  renderer:
    image: grafana/grafana-image-renderer:latest
    network_mode: host
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: "udp://n100d:514"
        tag: "grafana-renderer"
    environment:
      ENABLE_METRICS: "true"
